collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
#  - scope:
#      path: ""
#      type: "authors"
#    values:
#      layout: "author"
#  - scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


    #theme: just-the-docs
    #theme: beautiful-jekyll-theme
theme: minima



title: ""
  #email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This portfolio page has been created to provide you with a
  convenient way to familiarize yourself with the projects,
  publications, and areas of expertise that I am involved in.
#baseurl: "" # the subpath of your site, e.g. /blog
  #url: "" # the base hostname & protocol for your site, e.g. http://example.com
  #twitter_username: jekyllrb
github_username:  alireza-mahmoodi
linkedin_username: alireza-b-mahmoodi
