collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
#  - scope:
#      path: ""
#      type: "authors"
#    values:
#      layout: "author"
#  - scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


    #theme: just-the-docs
    #theme: beautiful-jekyll-theme
theme: minima



  #title: Cyrus
  #email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  #baseurl: "" # the subpath of your site, e.g. /blog
  #url: "" # the base hostname & protocol for your site, e.g. http://example.com
  #twitter_username: jekyllrb
github_username:  alireza-mahmoodi
linkedin_username: alireza-b-mahmoodi
